package AdditionApp;


/**
* AdditionApp/AdditionOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addition.idl
* Friday, March 15, 2019 8:04:32 PM BRT
*/

public interface AdditionOperations 
{
  int add (int a, int b);
  void shutdown ();
} // interface AdditionOperations
